name: Backend CI/CD

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend
    
jobs:
  Heroku:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build
        
      - name: Deploy to Heroku
        run: |
          cd ../
          git config --global user.name ${{secrets.NAME}}
          git config --global user.email ${{secrets.EMAIL}}
          git subtree split --prefix backend -b local
          git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/onu-uno.git local --force
