name: Backend CI/CD

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
  Heroku:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: |
          cd ../
          git config --global user.name ${{secrets.NAME}}
          git config --global user.email ${{secrets.EMAIL}}
          git subtree split --prefix backend -b local
          git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/onu-uno.git local:master --force
